name: Harpoon
options:
  bundleIdPrefix: dev.kevingyori
settings:
  base:
    SWIFT_VERSION: 6.0
    MACOSX_DEPLOYMENT_TARGET: 14.0
targets:
  Harpoon:
    type: application
    platform: macOS
    sources:
      - Harpoon
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.kevingyori.Harpoon
        PRODUCT_NAME: Harpoon
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_CFBundleDisplayName: Harpoon
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        INFOPLIST_KEY_LSUIElement: YES
        INFOPLIST_KEY_NSPrincipalClass: NSApplication
        DEVELOPMENT_TEAM: ""
